--- #YAML:1.0
name:                Gtk2-GoBoard
version:             1.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Games::Go::SimpleBoard:        0
    Gtk2:                          1.043
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
